@echo off
echo Starting zookeeper...
start "zookeeper" "zookeeper-3.4.6\bin\zkServer.cmd"
echo Starting redis...
start "redis" "redis-x64-3.0.500\redis-server.exe"
echo Starting activemq...
start "activemq" "activemq\bin\win64\activemq.bat"
#echo Starting nginx...
#start "nginx" "nginx-1.10.1\start.bat"
echo Starting zookeeper client...
start "zookeeper" "zookeeper-3.4.6\bin\zkCli.cmd"